language: php
php:
- '7.0'
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/plugin-health-check
  - secure: TDWFNpejshqtn+BgQPh/urFJ+NBkq8Kbn0Oyqf+jHCRlNW84ipB+VPZhKdEyj3/3RDH07su1LleqnYw4DFnzPVYhJg1wRcSZQVgkH8HwNLHA1MpXmUeta4wMvU+A3FRuztkj62DdMRoEPKdVBhulGT6yETIr+6AN92N+h3it5XACy63F9y2lX0LsMHXrIHNf0j4OIM9jEUOcQxswOjP8DOSCFeAFej1VXgrK1ozDZIQ4isYmO+WFufhMmwbRuxetNkAf4iKx1mRwM4Wfp2sswnhSeU9V4quBjN3OjSAEtqRm0eg/ieXzJDoLBtiORDeno1Of18eAjR8YAvApZNC9FT23AbqBM6LuZRSnbjKrlXO1VeJGRNtfAZnCo/GNwicAaMISCLoVqcqqpfO2EsXVq+q5Sw/1klMgs5WP1lcVV36gh+Q27wIA5xyowQlwKMZNWe3GWh1n5gZbpFTQ8Wswe16B4zcY9ozSzfbJhvHfeLQjrKmiB+b+1w3lBS74qNBouftUK3Ewmv6ZXEaRuUrjy5O27AYOUl7C0PUvOlcP+OT5LT20BmodUjDofiqQr7HonRjaxTqvVN8Qp/mrTpBz/CZ6s9GbG8dOCTcEG3kr1UhtpThnc8WJzUOAWPQwCRLlLVAS6zYnEF/gokI00nBsttcvNA+Llmkijcq2JaugLxA=
  - secure: qu0K/wLc1Ed0cn6lT9EE1cUOOUmxcC9gg1SnIihQ0XIJSkU6KbnxiSzlTx2zEA7R94AK+CRKcy7CLWIp+DfTqsH5m/MKYLER5we9Dxsy19lZKpvH/CDF/a4bYLOyoq2PRSKIKP7dPsp8wTAEGPg99qBd0oK54po+WkXAU3jmKEUN4xR0bi6wb/Fi3eSYZ08udw8M5v5aX87FfzRzuzgtEsmTr8NG1GZoNz9fk2Og8e5ZoAYMVUYyfddA6Ez2XVQ8MmIWETMIJx1G95KE29RPCWIUCvzowuDJ/AH1ZCxFlH90gRsYN/XIMV+cdJMknWX922XKTvKUk6//AzJkPqgj/vYFGHyUosJ0do6AbbYkbILBzNrTti4G1PTi2Jp0/ZklWtikcyNwO0jKq2EKGMQKQRmUM65762Bkjt9H6r4NzsjwOEabWMVHZDHgUaCz0QVMcPJnZ4kJihVzvtG1dqNbPqfFe73LTF9ZeTo8dP4UaQb8gXFQelfUO8DiUKtKwyLn60LcEXVHUogkP71TBGuppEk0hhv9XjyuyKh8h1bn6satzZ8Q+sURjy5SvpD763IrwsYUyKbFVJF4aobJwsO7ufDwLbAH3D9aU89gwnVU+4/VDaBw+0bI3i7ugbzeNy6jDAIJJrIuuRcn/qIN4iztQbne+9IC9v+uqb2Ha5dB9Rs=
