language: php
php:
- '7.0'
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/plugin-health-check
  - secure: TDWFNpejshqtn+BgQPh/urFJ+NBkq8Kbn0Oyqf+jHCRlNW84ipB+VPZhKdEyj3/3RDH07su1LleqnYw4DFnzPVYhJg1wRcSZQVgkH8HwNLHA1MpXmUeta4wMvU+A3FRuztkj62DdMRoEPKdVBhulGT6yETIr+6AN92N+h3it5XACy63F9y2lX0LsMHXrIHNf0j4OIM9jEUOcQxswOjP8DOSCFeAFej1VXgrK1ozDZIQ4isYmO+WFufhMmwbRuxetNkAf4iKx1mRwM4Wfp2sswnhSeU9V4quBjN3OjSAEtqRm0eg/ieXzJDoLBtiORDeno1Of18eAjR8YAvApZNC9FT23AbqBM6LuZRSnbjKrlXO1VeJGRNtfAZnCo/GNwicAaMISCLoVqcqqpfO2EsXVq+q5Sw/1klMgs5WP1lcVV36gh+Q27wIA5xyowQlwKMZNWe3GWh1n5gZbpFTQ8Wswe16B4zcY9ozSzfbJhvHfeLQjrKmiB+b+1w3lBS74qNBouftUK3Ewmv6ZXEaRuUrjy5O27AYOUl7C0PUvOlcP+OT5LT20BmodUjDofiqQr7HonRjaxTqvVN8Qp/mrTpBz/CZ6s9GbG8dOCTcEG3kr1UhtpThnc8WJzUOAWPQwCRLlLVAS6zYnEF/gokI00nBsttcvNA+Llmkijcq2JaugLxA=
  - secure: CXKpVk7crWtmv6U9eK8+nEJ1RnBNYROAKXvJzhDtQZdeCSi2KHnL+AWFWTNxtSWv9wpXdmeDQpZm3D7d/mSHOK1WsdkItHtqFzZAXY4AWlSVLjiYUoaleIPkoBLOratFl7puZa5mA1xw+xURNttbrqcZJZqfq6c6wam+/A+MzdOVb4t918plRvIz0sGDVSEaJLzhlKpbEurPJra1WiseUo4S9EiC3TKoz2FC0yUylrkN/7k9Yv6C6EMKG9KxcIHkyfjdYtuROkHpjP7+FD+xdl0475Y1x1F/rPL58L+4tkAeWSTtiTpF3d9jlLFAIxf0kKbBTGz6YKDEg3VNcXVUPWq+2VyAuU/qNcMlmQeUYK+GBCiwDyMIgT10WM7N6FvwPxtufUywMwbD+LgqVdr0fMktz0Mw/SvLGOizltBORTAGHsUhgmK6qipG8s0oz1045pPKIMWqrFX5FVGznRmivD/trvjV3yF+b8NJB0dUQjGAxpNQf2lWoWJ5+CutqLruZwoi/Os4AuWwvK90dZEISkJIOwEHLicjbinq//9i1F31/QpU4PBJTDmJZoplKHXGDiZQZ4uQaZoOre7cvaxI8uVSRyOb5kaDcxbFKRIvNWw1BHD1Za8MyK8Ojas9JyiEcOzBWQ97y4g2M4R2woxuoo3RmPEXRkcznS4iy3PPC6g=
